const hmsModules = {
  departments: {
    label: 'Departments',
    table: 'departments',
    searchFields: ['name', 'description'],
    fields: [
      { name: 'name', label: 'Department Name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'created_at', label: 'Created At' },
    ],
  },
  doctors: {
    label: 'Doctors',
    table: 'doctors',
    searchFields: ['full_name', 'department', 'specialization', 'phone', 'email', 'status'],
    fields: [
      { name: 'full_name', label: 'Doctor Name', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'text', required: true },
      { name: 'specialization', label: 'Specialization', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'schedule', label: 'Schedule', type: 'text' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: ['Active', 'On Leave', 'Off Duty'],
      },
    ],
    columns: [
      { key: 'full_name', label: 'Doctor' },
      { key: 'department', label: 'Department' },
      { key: 'specialization', label: 'Specialization' },
      { key: 'phone', label: 'Phone' },
      { key: 'email', label: 'Email' },
      { key: 'schedule', label: 'Schedule' },
      { key: 'status', label: 'Status' },
      { key: 'created_at', label: 'Created At' },
    ],
  },
  appointments: {
    label: 'Appointments',
    table: 'appointments',
    searchFields: ['patient_name', 'doctor_name', 'status', 'notes'],
    fields: [
      { name: 'patient_name', label: 'Patient Name', type: 'text', required: true },
      { name: 'doctor_name', label: 'Doctor Name', type: 'text', required: true },
      { name: 'appointment_date', label: 'Appointment Date', type: 'date', required: true },
      { name: 'appointment_time', label: 'Appointment Time', type: 'text' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: ['Booked', 'Rescheduled', 'Cancelled', 'Completed'],
      },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
    columns: [
      { key: 'patient_name', label: 'Patient' },
      { key: 'doctor_name', label: 'Doctor' },
      { key: 'appointment_date', label: 'Date' },
      { key: 'appointment_time', label: 'Time' },
      { key: 'status', label: 'Status' },
      { key: 'notes', label: 'Notes' },
      { key: 'created_at', label: 'Created At' },
    ],
  },
  admissions: {
    label: 'Admissions',
    table: 'admissions',
    searchFields: ['patient_name', 'ward', 'admission_type', 'status', 'notes'],
    fields: [
      { name: 'patient_name', label: 'Patient Name', type: 'text', required: true },
      { name: 'ward', label: 'Ward', type: 'text' },
      { name: 'admission_type', label: 'Admission Type', type: 'text' },
      { name: 'admission_date', label: 'Admission Date', type: 'date', required: true },
      { name: 'discharge_date', label: 'Discharge Date', type: 'date' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: ['Admitted', 'Discharged', 'Transferred'],
      },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
    columns: [
      { key: 'patient_name', label: 'Patient' },
      { key: 'ward', label: 'Ward' },
      { key: 'admission_type', label: 'Admission Type' },
      { key: 'admission_date', label: 'Admission Date' },
      { key: 'discharge_date', label: 'Discharge Date' },
      { key: 'status', label: 'Status' },
      { key: 'notes', label: 'Notes' },
      { key: 'created_at', label: 'Created At' },
    ],
  },
  medical_records: {
    label: 'Medical Records',
    table: 'medical_records',
    searchFields: ['patient_name', 'diagnosis', 'prescriptions', 'treatment_history', 'medical_reports'],
    fields: [
      { name: 'patient_name', label: 'Patient Name', type: 'text', required: true },
      { name: 'diagnosis', label: 'Diagnosis', type: 'text' },
      { name: 'prescriptions', label: 'Prescriptions', type: 'textarea' },
      { name: 'treatment_history', label: 'Treatment History', type: 'textarea' },
      { name: 'medical_reports', label: 'Medical Reports', type: 'textarea' },
      { name: 'record_date', label: 'Record Date', type: 'date', required: true },
    ],
    columns: [
      { key: 'patient_name', label: 'Patient' },
      { key: 'diagnosis', label: 'Diagnosis' },
      { key: 'prescriptions', label: 'Prescriptions' },
      { key: 'treatment_history', label: 'Treatment History' },
      { key: 'medical_reports', label: 'Medical Reports' },
      { key: 'record_date', label: 'Record Date' },
      { key: 'created_at', label: 'Created At' },
    ],
  },
  laboratory_tests: {
    label: 'Laboratory Tests',
    table: 'laboratory_tests',
    searchFields: ['patient_name', 'test_name', 'sample_collection_status', 'result_entry', 'report_generation', 'status'],
    fields: [
      { name: 'patient_name', label: 'Patient Name', type: 'text', required: true },
      { name: 'test_name', label: 'Test Name', type: 'text', required: true },
      {
        name: 'sample_collection_status',
        label: 'Sample Collection Status',
        type: 'select',
        options: ['Pending', 'Collected', 'Processed'],
      },
      { name: 'result_entry', label: 'Result Entry', type: 'textarea' },
      { name: 'report_generation', label: 'Report Generation', type: 'textarea' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: ['Requested', 'In Progress', 'Completed'],
      },
    ],
    columns: [
      { key: 'patient_name', label: 'Patient' },
      { key: 'test_name', label: 'Test Name' },
      { key: 'sample_collection_status', label: 'Sample Status' },
      { key: 'result_entry', label: 'Result Entry' },
      { key: 'report_generation', label: 'Report' },
      { key: 'status', label: 'Status' },
      { key: 'created_at', label: 'Created At' },
    ],
  },
  pharmacy_items: {
    label: 'Pharmacy',
    table: 'pharmacy_items',
    searchFields: ['medicine_name', 'prescription_processing', 'status'],
    fields: [
      { name: 'medicine_name', label: 'Medicine Name', type: 'text', required: true },
      { name: 'stock_quantity', label: 'Stock Quantity', type: 'number', required: true },
      { name: 'expiry_date', label: 'Expiry Date', type: 'date' },
      { name: 'prescription_processing', label: 'Prescription Processing', type: 'textarea' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: ['Available', 'Low Stock', 'Out of Stock', 'Expired'],
      },
      { name: 'unit_price', label: 'Unit Price', type: 'number' },
    ],
    columns: [
      { key: 'medicine_name', label: 'Medicine' },
      { key: 'stock_quantity', label: 'Stock' },
      { key: 'expiry_date', label: 'Expiry Date' },
      { key: 'prescription_processing', label: 'Processing' },
      { key: 'status', label: 'Status' },
      { key: 'unit_price', label: 'Unit Price' },
      { key: 'created_at', label: 'Created At' },
    ],
  },
  billing_records: {
    label: 'Billing',
    table: 'billing_records',
    searchFields: ['patient_name', 'invoice_number', 'status'],
    fields: [
      { name: 'patient_name', label: 'Patient Name', type: 'text', required: true },
      { name: 'consultation_charges', label: 'Consultation Charges', type: 'number' },
      { name: 'laboratory_charges', label: 'Laboratory Charges', type: 'number' },
      { name: 'pharmacy_charges', label: 'Pharmacy Charges', type: 'number' },
      { name: 'admission_charges', label: 'Admission Charges', type: 'number' },
      { name: 'invoice_number', label: 'Invoice Number', type: 'text', required: true },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: ['Unpaid', 'Partial', 'Paid', 'Voided'],
      },
    ],
    columns: [
      { key: 'patient_name', label: 'Patient' },
      { key: 'consultation_charges', label: 'Consultation' },
      { key: 'laboratory_charges', label: 'Laboratory' },
      { key: 'pharmacy_charges', label: 'Pharmacy' },
      { key: 'admission_charges', label: 'Admission' },
      { key: 'invoice_number', label: 'Invoice Number' },
      { key: 'status', label: 'Status' },
      { key: 'created_at', label: 'Created At' },
    ],
  },
  payments: {
    label: 'Payments',
    table: 'payments',
    searchFields: ['invoice_number', 'patient_name', 'payment_method', 'status'],
    fields: [
      { name: 'invoice_number', label: 'Invoice Number', type: 'text', required: true },
      { name: 'patient_name', label: 'Patient Name', type: 'text', required: true },
      { name: 'amount_paid', label: 'Amount Paid', type: 'number', required: true },
      { name: 'payment_method', label: 'Payment Method', type: 'text' },
      { name: 'payment_date', label: 'Payment Date', type: 'date', required: true },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: ['Recorded', 'Reversed', 'Pending'],
      },
    ],
    columns: [
      { key: 'invoice_number', label: 'Invoice Number' },
      { key: 'patient_name', label: 'Patient' },
      { key: 'amount_paid', label: 'Amount Paid' },
      { key: 'payment_method', label: 'Method' },
      { key: 'payment_date', label: 'Payment Date' },
      { key: 'status', label: 'Status' },
      { key: 'created_at', label: 'Created At' },
    ],
  },
  employees: {
    label: 'Staff Management',
    table: 'employees',
    searchFields: ['full_name', 'role', 'department', 'attendance', 'leave_records', 'phone'],
    fields: [
      { name: 'full_name', label: 'Full Name', type: 'text', required: true },
      { name: 'role', label: 'Role', type: 'text', required: true },
      { name: 'department', label: 'Department', type: 'text' },
      {
        name: 'attendance',
        label: 'Attendance',
        type: 'select',
        options: ['Present', 'Absent', 'On Leave'],
      },
      { name: 'leave_records', label: 'Leave Records', type: 'textarea' },
      { name: 'phone', label: 'Phone', type: 'text' },
    ],
    columns: [
      { key: 'full_name', label: 'Name' },
      { key: 'role', label: 'Role' },
      { key: 'department', label: 'Department' },
      { key: 'attendance', label: 'Attendance' },
      { key: 'leave_records', label: 'Leave Records' },
      { key: 'phone', label: 'Phone' },
      { key: 'created_at', label: 'Created At' },
    ],
  },
};

module.exports = hmsModules;